name: Wardstone
version: ${project.version}
main: com.moonlight.coreprotect.CoreProtectPlugin
api-version: 1.21
description: Sistema de nucleos de proteccion con 20 niveles y animaciones de particulas
author: MoonlightMC
website: moonlightmc.xyz
depend: [Vault]
softdepend: [BlueMap]

commands:
  cores:
    description: Comando principal del plugin de nucleos
    usage: /<command> [tienda|info|remove|add|kick]
    aliases: [nucleo, nucleos]
  admincore:
    description: Comandos de administracion
    usage: /<command> [deleteprotection]
    permission: coreprotect.admin
  gaspi:
    description: Reclamar recompensa unica de llaves
    usage: /<command>
  finishers:
    description: Menu de Death Finishers
    usage: /<command>
    aliases: [finisher, deathfinisher]

permissions:
  coreprotect.use:
    description: Permite usar el sistema de nucleos
    default: true
  coreprotect.admin:
    description: Permisos de administrador
    default: op
  wardstone.vip.luna:
    description: Acceso al nucleo VIP Luna
    default: false
  wardstone.vip.nova:
    description: Acceso al nucleo VIP Nova
    default: false
  wardstone.vip.eclipse:
    description: Acceso al nucleo VIP Eclipse
    default: false
  wardstone.vip.moonlord:
    description: Acceso al nucleo VIP MoonLord
    default: false
