name: CoreProtect
version: ${project.version}
main: com.moonlight.coreprotect.CoreProtectPlugin
api-version: 1.21
description: Sistema de nucleos de proteccion con 20 niveles y animaciones de particulas
author: MoonlightMC
website: moonlightmc.xyz
depend: [Vault]
softdepend: [BlueMap]

commands:
  cores:
    description: Comando principal del plugin de nucleos
    usage: /<command> [tienda|info|remove|add|kick]
    aliases: [core, nucleo, nucleos]
  admincore:
    description: Comandos de administracion
    usage: /<command> [deleteprotection]
    permission: coreprotect.admin
  rpg:
    description: Ver tu perfil RPG
    usage: /rpg
  class:
    description: Elegir tu clase RPG
    usage: /class
  stats:
    description: Asignar puntos de estadistica
    usage: /stats
  skills:
    description: Ver arbol de habilidades
    usage: /skills
  skill:
    description: Usar una habilidad RPG
    usage: /skill <nombre>
  linkmc:
    description: Vincular cuenta web con codigo
    usage: /linkmc
  coreprotect:linkvalidate:
    description: Validar codigo de vinculacion (RCON)
    usage: /coreprotect:linkvalidate <code>
    permission: coreprotect.admin

permissions:
  coreprotect.use:
    description: Permite usar el sistema de nucleos
    default: true
  coreprotect.admin:
    description: Permisos de administrador
    default: op
